# permissions for end users to view dataretrievers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: datamigrator
    app.kubernetes.io/managed-by: kustomize
  name: dataretriever-viewer-role
rules:
- apiGroups:
  - etl.com
  resources:
  - dataretrievers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etl.com
  resources:
  - dataretrievers/status
  verbs:
  - get
