---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - etl.etl.com
  resources:
  - datamigrators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etl.etl.com
  resources:
  - datamigrators/finalizers
  verbs:
  - update
- apiGroups:
  - etl.etl.com
  resources:
  - datamigrators/status
  verbs:
  - get
  - patch
  - update
