---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - etl.com
  resources:
  - dataretrievers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etl.com
  resources:
  - dataretrievers/finalizers
  verbs:
  - update
- apiGroups:
  - etl.com
  resources:
  - dataretrievers/status
  verbs:
  - get
  - patch
  - update
